name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
        pyzeal
    - name: Lint with flake8 and pylint
      run: |
        flake8 --count src tests
        pylint --fail-under=8 src tests
    - name: Type checking with mypy
      run: |
        mypy src tests
    - name: Check docstring coverage
      run: |
        docstr-coverage -m -f -F 85.0 src tests
    - name: Test with pytest
      run: |
        pytest tests
