name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"
        pyzeal
    - name: Lint with pylama
      run: |
        pylama pyzeal
    - name: Lint with pylint
      run: |
        pylint pyzeal
    - name: Type checking with mypy
      run: |
        mypy pyzeal
    - name: Check docstring coverage
      run: |
        docstr-coverage -m -f -F 85.0 pyzeal
    - name: Check json schemata
      run: |
        check-jsonschema -v --schemafile pyzeal/settings/settings_schema.json pyzeal/settings/default_settings.json
      if: ${{ matrix.os }} == 'ubuntu-latest'
    - name: Test with pytest
      run: |
        pytest -n auto pyzeal/tests
        pytest -m "locator" pyzeal
