name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
        pyzeal
    - name: Lint with flake8 and pylint
      run: |
        flake8 --count src/
        flake8 --count test/
        flake8 --count benchmarks/
        pylint --fail-under=8 src/
        pylint --fail-under=8 test/
    - name: Test with pytest
      run: |
        pytest test/
    - name: Type checking with mypy
      run: |
        mypy src/
        mypy test/
        mypy benchmarks/
    - name: Check docstring coverage
      run: |
        docstr-coverage -m -f -F 80.0 src/
        docstr-coverage -m -f -F 90.0 test/
        docstr-coverage -m -f -F 90.0 benchmarks/
