name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pylint mypy docstr-coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8 and pylint
      run: |
        flake8 --count src/
        flake8 --count test/test_pkg1/*.py
        pylint src/
        pylint test/test_pkg1/*.py
    - name: Test with pytest
      run: |
        pytest test/
    - name: Type checking with mypy
      run: |
        mypy src/
    - name: Check docstring coverage
      run: |
        docstr-coverage -m -f -F 80.0 src/
